#!/usr/bin/env bash

set -u

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_DIR="$SCRIPT_DIR"

EXECUTABLE="$REPO_DIR/llmp"
METADATA_FILE="$REPO_DIR/.llmp-install-metadata"

if [[ ! -x "$EXECUTABLE" ]]; then
  printf 'install.sh: executable not found or not executable: %s\n' "$EXECUTABLE" >&2
  exit 1
fi

if [[ ! -d "$REPO_DIR/prompts" ]]; then
  printf 'install.sh: prompts directory not found: %s\n' "$REPO_DIR/prompts" >&2
  exit 1
fi

printf 'Where should the llmp executable be linked?\n'
printf 'Executable directory [%s]: ' "$HOME/.local/bin"
read -r BIN_DIR

if [[ -z "$BIN_DIR" ]]; then
  BIN_DIR="$HOME/.local/bin"
fi

BIN_DIR="${BIN_DIR/#\~/$HOME}"
BIN_LINK="$BIN_DIR/llmp"

# Safety check before creating anything.
if [[ -e "$BIN_LINK" || -L "$BIN_LINK" ]]; then
  printf 'install.sh: refusing to overwrite existing path: %s\n' "$BIN_LINK" >&2
  exit 1
fi

# Create the executable directory.
if ! mkdir -p "$BIN_DIR"; then
  printf 'install.sh: could not create executable directory: %s\n' "$BIN_DIR" >&2
  exit 1
fi

# Create the link.
if ! ln -s "$EXECUTABLE" "$BIN_LINK"; then
  printf 'install.sh: failed to create executable symlink: %s\n' "$BIN_LINK" >&2
  exit 1
fi

# Save exact path and target for safe uninstall.
if ! cat > "$METADATA_FILE" <<EOF
# Generated by install.sh. Do not edit unless you know what you are doing.
REPO_DIR=$(printf '%q' "$REPO_DIR")
BIN_LINK=$(printf '%q' "$BIN_LINK")
BIN_TARGET=$(printf '%q' "$EXECUTABLE")
EOF
then
  printf 'install.sh: could not write install metadata: %s\n' "$METADATA_FILE" >&2
  rm -f "$BIN_LINK"
  exit 1
fi

printf '\nInstalled successfully.\n'
printf '  executable: %s -> %s\n' "$BIN_LINK" "$EXECUTABLE"

case ":$PATH:" in
  *":$BIN_DIR:"*)
    ;;
  *)
    printf '\nWarning: %s is not in PATH.\n' "$BIN_DIR"
    printf 'You may need to add it to your shell configuration.\n'
    ;;
esac

printf '\nRun: llmp\n'
